### ISSUE TITLE
OCR Not working

### ISSUE THREAD

**Issue by DanMcgraw** [deluan/lookup#9]
I tried using ocr on several simple files and it returns nothing, the font folder seems to only have a couple of characters

**Comment by DanMcgraw** [comment]
The example works, but the font folder does not contain alpha characters, only numeric.

**Comment by deluan** [comment]
> The example works, but the font folder does not contain alpha characters, only numeric.

That is correct, the fonts are for that example only, you'll need to provide fonts for what you want to read.

Maybe you misunderstood how it works. To use this OCR you need to provide the fonts for the specific image you want to read. The library focus is to read information from screen, to be use in robot and test software. It is not a generic OCR that meant to read anything from anywhere. This approach with specific fonts for each task makes its performance goes up to 100% and make it very fast, comparable to other solutions like Tesseract OCR, but it requires more work upfront.

Let me know if you have further questions.
